// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHfCsmsFB0KWrVn0GIZpQ5KgVCmeEg8E',
    appId: '1:677005382014:web:1457a39bf19912618b232f',
    messagingSenderId: '677005382014',
    projectId: 'icts-3b67c',
    authDomain: 'icts-3b67c.firebaseapp.com',
    storageBucket: 'icts-3b67c.appspot.com',
    measurementId: 'G-BBY1MLWBKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0PrPLqB_eCpEb_Voh0V_KW7849uE9no',
    appId: '1:677005382014:android:9b389927025af63b8b232f',
    messagingSenderId: '677005382014',
    projectId: 'icts-3b67c',
    storageBucket: 'icts-3b67c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF9oH6uY2O5jE1rCB1eiCgR-XdB_dZE1o',
    appId: '1:677005382014:ios:9dc514d238ff65df8b232f',
    messagingSenderId: '677005382014',
    projectId: 'icts-3b67c',
    storageBucket: 'icts-3b67c.appspot.com',
    iosBundleId: 'com.example.icts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF9oH6uY2O5jE1rCB1eiCgR-XdB_dZE1o',
    appId: '1:677005382014:ios:9dc514d238ff65df8b232f',
    messagingSenderId: '677005382014',
    projectId: 'icts-3b67c',
    storageBucket: 'icts-3b67c.appspot.com',
    iosBundleId: 'com.example.icts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOHfCsmsFB0KWrVn0GIZpQ5KgVCmeEg8E',
    appId: '1:677005382014:web:a508bf32a922d1548b232f',
    messagingSenderId: '677005382014',
    projectId: 'icts-3b67c',
    authDomain: 'icts-3b67c.firebaseapp.com',
    storageBucket: 'icts-3b67c.appspot.com',
    measurementId: 'G-XSFWKLCKHP',
  );
}
